CREATE TABLE health_data (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    device_id UUID,
    data_type VARCHAR(50) NOT NULL,
    data_value DECIMAL(10,3),
    unit VARCHAR(20),
    systolic_pressure DECIMAL(5,1),
    diastolic_pressure DECIMAL(5,1),
    heart_rate INTEGER,
    blood_sugar DECIMAL(5,2),
    temperature DECIMAL(4,2),
    fall_detected BOOLEAN DEFAULT FALSE,
    fall_severity INTEGER DEFAULT 0,
    location_latitude DECIMAL(10,8),
    location_longitude DECIMAL(11,8),
    measurement_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    abnormal_flag INTEGER DEFAULT 0,
    ai_analysis_result JSONB,
    alert_sent BOOLEAN DEFAULT FALSE,
    reviewed_by UUID,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);