CREATE TABLE profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL UNIQUE,
    real_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(100),
    gender INTEGER DEFAULT 0,
    birth_date DATE,
    age INTEGER,
    region_code VARCHAR(20) DEFAULT '420102',
    address TEXT,
    emergency_contact_name VARCHAR(50),
    emergency_contact_phone VARCHAR(20),
    blood_type VARCHAR(5),
    chronic_diseases JSONB DEFAULT '[]'::jsonb,
    allergies JSONB DEFAULT '[]'::jsonb,
    current_medications JSONB DEFAULT '[]'::jsonb,
    user_type INTEGER DEFAULT 2,
    status INTEGER DEFAULT 1,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);