CREATE TABLE service_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    appointment_id UUID NOT NULL,
    elderly_id UUID NOT NULL,
    worker_id UUID,
    order_number VARCHAR(50) UNIQUE NOT NULL,
    service_type VARCHAR(50) NOT NULL,
    scheduled_time TIMESTAMP NOT NULL,
    estimated_duration INTEGER,
    actual_start_time TIMESTAMP,
    actual_end_time TIMESTAMP,
    pickup_location TEXT,
    destination_location TEXT,
    distance DECIMAL(10,2),
    base_fee DECIMAL(10,2),
    distance_fee DECIMAL(10,2),
    time_fee DECIMAL(10,2),
    total_fee DECIMAL(10,2),
    payment_status VARCHAR(50) DEFAULT 'unpaid',
    payment_method VARCHAR(50),
    order_status VARCHAR(50) DEFAULT 'pending',
    dispatch_time TIMESTAMP,
    accepted_time TIMESTAMP,
    arrived_time TIMESTAMP,
    completed_time TIMESTAMP,
    cancelled_time TIMESTAMP,
    cancellation_reason TEXT,
    rating INTEGER,
    review_content TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);